name: CI

on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node v15
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install && npm install -g @lhci/cli@0.6.x

      - name: Build site
        run: npm run export
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          AIRTABLE_CHAPTER_BASE_APP_ID: ${{ secrets.AIRTABLE_CHAPTER_BASE_APP_ID }}

      - name: Run Lighthouse
        run: lhci autorun
        # https://github.com/apps/lighthouse-ci
        # for displaying lighthouse results below PRs
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node v15
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run ci
        env:
          # needed to fetch website content
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          # needed to simulate form submission to Airtable test base
          AIRTABLE_CHAPTER_BASE_APP_ID: ${{ secrets.AIRTABLE_CHAPTER_BASE_APP_ID }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          # needed to perform Google Maps API place auto-completion when entering
          # the signup form address field
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
