name: Lighthouse

on: [push, pull_request]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 17
          cache: yarn

      - name: Install dependencies
        run: yarn && yarn add @lhci/cli

      - name: Build site
        run: yarn build
        env:
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          # to prevent penalty 'Browser errors were logged to the console' from
          # 'Invalid appId: undefined' in Lighthouse CI
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}

      - name: Run Lighthouse
        run: yarn lhci autorun
        # configure https://github.com/apps/lighthouse-ci for this repo
        # to display Lighthouse results below PRs
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
